language: node_js
node_js:
- '9.11'

cache:
  directories:
    - "node_modules"

script:
  - yarn test
  - yarn build
  # - echo my-custom-domain.ru > build/CNAME

deploy:
  provider: pages
  github-token: GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: build
  repo: mkiselyow/star_wars_build
  target-branch: master
  on:
    branch: master